### ISSUE TITLE
after generate user.sessions  how to use it?

### ISSUE THREAD

**Issue by jxwuqingyan** [Ansen/xshell2windterm#1]
have generate user.sessions file how to import to windterm?

**Comment by Ansen** [comment]
**Note: Please Backup origin user.sessions file at first**

Put it in  `${ProfilesDirectory}/.wind/profiles/default.v10/terminal/`, and restart Windterm.

**Note: Please Backup origin user.sessions file at first**

**Comment by jxwuqingyan** [comment]
thanks, it works well
